const WORDS = {
  easy: [
    ["Apple", "Orange"], ["Dog", "Cat"], ["Sun", "Moon"], ["Beach", "Pool"],
    ["Pizza", "Burger"], ["Rain", "Snow"], ["Bicycle", "Skateboard"], ["Chair", "Sofa"],
    ["Milk", "Juice"], ["Shoes", "Socks"], ["Book", "Magazine"], ["Pillow", "Blanket"],
    ["Banana", "Mango"], ["Kitchen", "Bathroom"], ["Winter", "Summer"], ["Bus", "Train"],
    ["Egg", "Bacon"], ["Umbrella", "Raincoat"], ["Candle", "Flashlight"], ["Garden", "Park"]
  ],
  medium: [
    ["Soccer", "Basketball"], ["Doctor", "Nurse"], ["Mountain", "Hill"], ["Guitar", "Piano"],
    ["Library", "Bookstore"], ["Painter", "Sculptor"], ["Volcano", "Earthquake"], ["Camping", "Hiking"],
    ["Wedding", "Funeral"], ["Astronaut", "Pilot"], ["Desert", "Jungle"], ["Chess", "Checkers"],
    ["Bakery", "Cafe"], ["Firefighter", "Police Officer"], ["Island", "Peninsula"], ["Marathon", "Sprint"],
    ["Castle", "Fortress"], ["Photographer", "Videographer"], ["Farmer", "Rancher"], ["Lawyer", "Judge"]
  ],
  hard: [
    ["Nostalgia", "Sentimentality"], ["Democracy", "Republic"], ["Inflation", "Recession"], ["Ambition", "Greed"],
    ["Meditation", "Hypnosis"], ["Philosophy", "Theology"], ["Sarcasm", "Irony"], ["Empathy", "Sympathy"],
    ["Bureaucracy", "Hierarchy"], ["Anarchy", "Chaos"], ["Metaphor", "Analogy"], ["Diplomacy", "Negotiation"],
    ["Renaissance", "Enlightenment"], ["Capitalism", "Consumerism"], ["Instinct", "Intuition"], ["Justice", "Fairness"],
    ["Loneliness", "Solitude"], ["Confidence", "Arrogance"], ["Curiosity", "Nosiness"], ["Freedom", "Independence"]
  ],
  mixed: [
    ["Sprite", "7UP"],
    ["Goji Berry", "Acai"],
    ["Pinecone", "Acorn"],
    ["Petra", "Acropolis"],
    ["Nike", "Adidas"],
    ["Crush", "Admirer"],
    ["Orphan", "Adopted"],
    ["Stepfather", "Adoptive Father"],
    ["Stepmother", "Adoptive Mother"],
    ["Wind", "Air"],
    ["Seatbelt", "Airbag"],
    ["Boeing", "Airbus"],
    ["Notification", "Alert"],
    ["Geometry", "Algebra"],
    ["Taj Mahal", "Alhambra"],
    ["Pegasus", "Alicorn"],
    ["E.T.", "Alien"],
    ["UFO", "Alien"],
    ["Crocodile", "Alligator"],
    ["Lonely", "Alone"],
    ["Intel", "AMD"],
    ["Rugby", "American Football"],
    ["iPhone", "Android"],
    ["Milky Way", "Andromeda"],
    ["Cupid", "Angel"],
    ["Sad", "Angry"],
    ["Wrist", "Ankle"],
    ["Angry", "Annoyed"],
    ["Spider", "Ant"],
    ["Firewall", "Antivirus"],
    ["Website", "App"],
    ["Tomato", "Apple"],
    ["Pomegranate", "Apple"],
    ["Spotify", "Apple Music"],
    ["Pumpkin Pie", "Apple Pie"],
    ["Gratitude", "Appreciation"],
    ["Peach", "Apricot"],
    ["Earth Day", "Arbor Day"],
    ["Darts", "Archery"],
    ["Librarian", "Archivist"],
    ["Stadium", "Arena"],
    ["Shield", "Armor"],
    ["Craft", "Art"],
    ["Vein", "Artery"],
    ["Guilty", "Ashamed"],
    ["Homework", "Assignment"],
    ["Moon", "Asteroid"],
    ["Astronomer", "Astrologer"],
    ["Astronomy", "Astrology"],
    ["Orphanage", "Asylum"],
    ["Podcast", "Audiobook"],
    ["Mother", "Aunt"],
    ["Rainbow", "Aurora"],
    ["Blizzard", "Avalanche"],
    ["Titanic", "Avatar"],
    ["Boulevard", "Avenue"],
    ["Handbag", "Backpack"],
    ["Raccoon", "Badger"],
    ["Tennis", "Badminton"],
    ["Pocket", "Bag"],
    ["Croissant", "Bagel"],
    ["Donut", "Bagel"],
    ["Pretzel", "Bagel"],
    ["Green Bean Casserole", "Baked Beans"],
    ["Butcher", "Baker"],
    ["Cooking", "Baking"],
    ["Harmony", "Balance"],
    ["Parachute", "Balloon"],
    ["Rudolph", "Bambi"],
    ["Choir", "Band"],
    ["Feast", "Banquet"],
    ["Nightclub", "Bar"],
    ["Pub", "Bar"],
    ["Thermometer", "Barometer"],
    ["Barista", "Bartender"],
    ["Garage", "Basement"],
    ["Cellar", "Basement"],
    ["Cornucopia", "Basket"],
    ["Guitar", "Bass"],
    ["Owl", "Bat"],
    ["Vampire", "Bat"],
    ["En-suite", "Bathroom"],
    ["War", "Battle"],
    ["Call of Duty", "Battlefield"],
    ["Ocean", "Bay"],
    ["Desert", "Beach"],
    ["Earmuffs", "Beanie"],
    ["Drum", "Beat"],
    ["Candy Crush", "Bejeweled"],
    ["Trust", "Belief"],
    ["Chest", "Belly"],
    ["Snapchat", "BeReal"],
    ["Beanie", "Beret"],
    ["Supernova", "Big Bang"],
    ["Bra", "Bikini"],
    ["Telescope", "Binoculars"],
    ["Science", "Biology"],
    ["Anniversary", "Birthday"],
    ["Cookie", "Biscuit"],
    ["Cornbread", "Biscuit"],
    ["Boxing Day", "Black Friday"],
    ["Poker", "Blackjack"],
    ["Towel", "Blanket"],
    ["Zeppelin", "Blimp"],
    ["Influencer", "Blogger"],
    ["Grape", "Blueberry"],
    ["Jazz", "Blues"],
    ["WiFi", "Bluetooth"],
    ["Cliff", "Bluff"],
    ["Motocross", "BMX"],
    ["Pig", "Boar"],
    ["Scrabble", "Boggle"],
    ["Library", "Bookstore"],
    ["Ultimate Frisbee", "Boomerang"],
    ["Angkor Wat", "Borobudur"],
    ["Bodyguard", "Bouncer"],
    ["Whiskey", "Bourbon"],
    ["Plate", "Bowl"],
    ["Tie", "Bowtie"],
    ["Present", "Box"],
    ["Bag", "Box"],
    ["Ring", "Bracelet"],
    ["Watch", "Bracelet"],
    ["Bark", "Branch"],
    ["Arc de Triomphe", "Brandenburg Gate"],
    ["Courage", "Bravery"],
    ["Stuffing", "Bread"],
    ["Dinner", "Breakfast"],
    ["Windy", "Breezy"],
    ["Poker", "Bridge"],
    ["Panties", "Briefs"],
    ["Sunny", "Bright"],
    ["Louvre", "British Museum"],
    ["Cufflink", "Brooch"],
    ["Macaron", "Brownie"],
    ["Comb", "Brush"],
    ["Trash Can", "Bucket"],
    ["Feast", "Buffet"],
    ["Virus", "Bug"],
    ["Cow", "Bull"],
    ["Forklift", "Bulldozer"],
    ["Tinder", "Bumble"],
    ["Skydiving", "Bungee Jumping"],
    ["Pizza", "Burger"],
    ["Sandwich", "Burger"],
    ["Taco", "Burrito"],
    ["Tree", "Bush"],
    ["Cheese", "Butter"],
    ["Zipper", "Button"],
    ["Cottage", "Cabin"],
    ["Drawer", "Cabinet"],
    ["Cookie", "Cache"],
    ["Restaurant", "Cafe"],
    ["Bakery", "Cafe"],
    ["Dining Room", "Cafeteria"],
    ["Phone", "Calculator"],
    ["Computer", "Calculator"],
    ["Thigh", "Calf"],
    ["Horse", "Camel"],
    ["School", "Camp"],
    ["Hiking", "Camping"],
    ["Chocolate", "Candy"],
    ["Treat", "Candy"],
    ["Rowing", "Canoeing"],
    ["Hat", "Cap"],
    ["Apron", "Cape"],
    ["Latte", "Cappuccino"],
    ["Shuttle", "Capsule"],
    ["Sailor", "Captain"],
    ["Sleigh", "Car"],
    ["Key", "Card"],
    ["Rickshaw", "Carriage"],
    ["Sculpture", "Carving"],
    ["Arcade", "Casino"],
    ["Coffin", "Casket"],
    ["Plantain", "Cassava"],
    ["Monopoly", "Catan"],
    ["Worm", "Caterpillar"],
    ["Influencer", "Celebrity"],
    ["Violin", "Cello"],
    ["Haunted House", "Cemetery"],
    ["Oatmeal", "Cereal"],
    ["Festival", "Ceremony"],
    ["Necklace", "Chain"],
    ["Throne", "Chair"],
    ["Battery", "Charger"],
    ["Pilot", "Chauffeur"],
    ["Chess", "Checkers"],
    ["Pharmacist", "Chemist"],
    ["Cranberry", "Cherry"],
    ["Acorn", "Chestnut"],
    ["Machu Picchu", "Chichen Itza"],
    ["Turkey", "Chicken"],
    ["Offspring", "Child"],
    ["Frostbite", "Chill"],
    ["Cheek", "Chin"],
    ["Fries", "Chips"],
    ["Statue of Liberty", "Christ the Redeemer"],
    ["Thanksgiving", "Christmas"],
    ["New Year's Day", "Christmas Eve"],
    ["St. Patrick's Day", "Cinco de Mayo"],
    ["Theater", "Cinema"],
    ["Courtroom", "City Hall"],
    ["Nail", "Claw"],
    ["Carving Knife", "Cleaver"],
    ["Server", "Client"],
    ["Hospital", "Clinic"],
    ["Cape", "Cloak"],
    ["Sponge", "Cloth"],
    ["Gobble", "Cluck"],
    ["Personal Trainer", "Coach"],
    ["Firewood", "Coal"],
    ["Tailor", "Cobbler"],
    ["Beetle", "Cockroach"],
    ["Algorithm", "Code"],
    ["Gaming", "Coding"],
    ["Salad", "Coleslaw"],
    ["Girlfriend", "Colleague"],
    ["School", "College"],
    ["Perfume", "Cologne"],
    ["Toothbrush", "Comb"],
    ["Clown", "Comedian"],
    ["Meteor", "Comet"],
    ["Relieved", "Comforted"],
    ["Traveling", "Commuting"],
    ["Watch", "Compass"],
    ["Symphony", "Concerto"],
    ["Shampoo", "Conditioner"],
    ["Proud", "Confident"],
    ["Embassy", "Consulate"],
    ["Freelancer", "Contractor"],
    ["Launchpad", "Control Center"],
    ["Supermarket", "Convenience Store"],
    ["Gingerbread", "Cookie"],
    ["Cold", "Cool"],
    ["Shell", "Coral"],
    ["Hallway", "Corridor"],
    ["Astronaut", "Cosmonaut"],
    ["Uniform", "Costume"],
    ["Brother", "Cousin"],
    ["Cherry", "Cranberry"],
    ["Mario Kart", "Crash Team Racing"],
    ["Milk", "Cream"],
    ["Waffle", "Crepe"],
    ["Baseball", "Cricket"],
    ["Knitting", "Crocheting"],
    ["Jigsaw Puzzle", "Crossword"],
    ["Ferry", "Cruise"],
    ["HTML", "CSS"],
    ["Muffin", "Cupcake"],
    ["Bowling", "Curling"],
    ["Syllabus", "Curriculum"],
    ["Spell", "Curse"],
    ["Pillow", "Cushion"],
    ["Tradition", "Custom"],
    ["Black Friday", "Cyber Monday"],
    ["Typhoon", "Cyclone"],
    ["Sword", "Dagger"],
    ["Vimeo", "Dailymotion"],
    ["Gymnastics", "Dance"],
    ["Singing", "Dancing"],
    ["Croissant", "Danish"],
    ["Fig", "Date"],
    ["Tamarind", "Date"],
    ["All Saints' Day", "Day of the Dead"],
    ["Marvel", "DC"],
    ["Credit Card", "Debit Card"],
    ["November", "December"],
    ["Winter", "December"],
    ["Centerpiece", "Decoration"],
    ["Architect", "Decorator"],
    ["Diploma", "Degree"],
    ["Thrilled", "Delighted"],
    ["God", "Demigod"],
    ["Mall", "Department Store"],
    ["Miserable", "Depressed"],
    ["Ancestor", "Descendant"],
    ["Oasis", "Desert"],
    ["Art", "Design"],
    ["Architecture", "Design"],
    ["Artist", "Designer"],
    ["Table", "Desk"],
    ["Frost", "Dew"],
    ["Heart", "Diamond"],
    ["Notebook", "Diary"],
    ["Pokemon", "Digimon"],
    ["Realm", "Dimension"],
    ["Raft", "Dinghy"],
    ["Dragon", "Dinosaur"],
    ["Politician", "Diplomat"],
    ["Actor", "Director"],
    ["Sad", "Disappointed"],
    ["Costume", "Disguise"],
    ["Chaos", "Disorder"],
    ["Swimming", "Diving"],
    ["Widow", "Divorcee"],
    ["Pier", "Dock"],
    ["Werewolf", "Dog"],
    ["Statue", "Doll"],
    ["Jenga", "Dominoes"],
    ["Charity", "Donation"],
    ["Horse", "Donkey"],
    ["League of Legends", "Dota 2"],
    ["Suspicious", "Doubtful"],
    ["Pigeon", "Dove"],
    ["Streaming", "Downloading"],
    ["Vampire", "Dracula"],
    ["Neuschwanstein", "Dracula's Castle"],
    ["Breeze", "Draft"],
    ["Hydra", "Dragon"],
    ["Painting", "Drawing"],
    ["Pilot", "Driver"],
    ["Garage", "Driveway"],
    ["Rainy", "Drizzle"],
    ["Pharmacy", "Drugstore"],
    ["Laundromat", "Dry Cleaner"],
    ["Nymph", "Dryad"],
    ["Chicken", "Duck"],
    ["Interstellar", "Dune"],
    ["Starbucks", "Dunkin'"],
    ["Sand", "Dust"],
    ["Elf", "Dwarf"],
    ["Planet", "Dwarf Planet"],
    ["Generation", "Dynasty"],
    ["Moped", "E-bike"],
    ["Eye", "Ear"],
    ["Headphones", "Earbuds"],
    ["Ornament", "Earring"],
    ["Ring", "Earring"],
    ["Tsunami", "Earthquake"],
    ["Passover", "Easter"],
    ["Stonehenge", "Easter Island"],
    ["Amazon", "eBay"],
    ["Spring Roll", "Egg Roll"],
    ["Ramadan", "Eid"],
    ["Knee", "Elbow"],
    ["Santa Claus", "Elf"],
    ["Moose", "Elk"],
    ["Love Letter", "Email"],
    ["Sympathetic", "Empathetic"],
    ["Burj Khalifa", "Empire State Building"],
    ["Dictionary", "Encyclopedia"],
    ["Scientist", "Engineer"],
    ["Architecture", "Engineering"],
    ["Amused", "Entertained"],
    ["Mudroom", "Entryway"],
    ["Jealous", "Envious"],
    ["Nature", "Environment"],
    ["Elevator", "Escalator"],
    ["Throat", "Esophagus"],
    ["L'Oreal", "Estee Lauder"],
    ["Bitcoin", "Ethereum"],
    ["Fiber Optic", "Ethernet"],
    ["Happy", "Excited"],
    ["Life", "Existence"],
    ["Eyelash", "Eyebrow"],
    ["Mask", "Face Paint"],
    ["Skype", "FaceTime"],
    ["Truth", "Fact"],
    ["Exhibition", "Fair"],
    ["Justice", "Fairness"],
    ["Angel", "Fairy"],
    ["Pixie", "Fairy"],
    ["Myth", "Fairy Tale"],
    ["Skyrim", "Fallout"],
    ["The Simpsons", "Family Guy"],
    ["Living Room", "Family Room"],
    ["Zoo", "Farm"],
    ["Gardening", "Farming"],
    ["Luck", "Fate"],
    ["Mother's Day", "Father's Day"],
    ["Leaf", "Feather"],
    ["Porsche", "Ferrari"],
    ["Carnival", "Festival"],
    ["Husband", "Fiancé"],
    ["Wife", "Fiancée"],
    ["Lacrosse", "Field Hockey"],
    ["Photography", "Filming"],
    ["Zelda", "Final Fantasy"],
    ["World of Warcraft", "Final Fantasy XIV"],
    ["Economics", "Finance"],
    ["Phoenix", "Firebird"],
    ["Mermaid", "Fish"],
    ["Lamp", "Flashlight"],
    ["Cloud", "Fog"],
    ["Cloudy", "Foggy"],
    ["Hand", "Foot"],
    ["Castle", "Fort"],
    ["Zombie", "Frankenstein"],
    ["Open Source", "Freeware"],
    ["English", "French"],
    ["Thursday", "Friday"],
    ["Boyfriend", "Friend"],
    ["Romance", "Friendship"],
    ["Myspace", "Friendster"],
    ["Mashed Potatoes", "Fries"],
    ["Dew", "Frost"],
    ["Hair", "Fur"],
    ["Mattress", "Futon"],
    ["Museum", "Gallery"],
    ["Workshop", "Garage"],
    ["Park", "Garden"],
    ["Farmer", "Gardener"],
    ["Scarecrow", "Gargoyle"],
    ["Wreath", "Garland"],
    ["Reunion", "Gathering"],
    ["Conservatory", "Gazebo"],
    ["History", "Geography"],
    ["Spanish", "German"],
    ["Meme", "GIF"],
    ["Camping", "Glamping"],
    ["Cup", "Glass"],
    ["Mirror", "Glass"],
    ["Contact Lenses", "Glasses"],
    ["Overcast", "Gloomy"],
    ["Tape", "Glue"],
    ["Elf", "Gnome"],
    ["Chess", "Go"],
    ["Sheep", "Goat"],
    ["Jurassic Park", "Godzilla"],
    ["Glasses", "Goggles"],
    ["Cable Car", "Gondola"],
    ["The Godfather", "Goodfellas"],
    ["Swan", "Goose"],
    ["Kiwi", "Gooseberry"],
    ["Blood", "Gore"],
    ["Monkey", "Gorilla"],
    ["Mayor", "Governor"],
    ["Map", "GPS"],
    ["Linguistics", "Grammar"],
    ["Niagara Falls", "Grand Canyon"],
    ["Lychee", "Grape"],
    ["Olive", "Grape"],
    ["Apple Cider", "Grape Juice"],
    ["Cricket", "Grasshopper"],
    ["Tombstone", "Grave"],
    ["Clay", "Gravel"],
    ["Grandma", "Great-Grandma"],
    ["Grandpa", "Great-Grandpa"],
    ["Sunroom", "Greenhouse"],
    ["Goblin", "Gremlin"],
    ["Spellbook", "Grimoire"],
    ["Howl", "Growl"],
    ["Godparent", "Guardian"],
    ["Master Bedroom", "Guest Bedroom"],
    ["Bedroom", "Guest Room"],
    ["Lips", "Gums"],
    ["Parkour", "Gymnastics"],
    ["Cheerleading", "Gymnastics"],
    ["Zara", "H&M"],
    ["Programmer", "Hacker"],
    ["Phishing", "Hacking"],
    ["Flurry", "Hailstone"],
    ["Easter", "Halloween"],
    ["Turkey", "Ham"],
    ["Rabbit", "Hamster"],
    ["Water Polo", "Handball"],
    ["Dodgeball", "Handball"],
    ["Tissue", "Handkerchief"],
    ["Steering Wheel", "Handlebar"],
    ["Hug", "Handshake"],
    ["Calligraphy", "Handwriting"],
    ["Glider", "Hang Glider"],
    ["Flash Drive", "Hard Drive"],
    ["Crown", "Hat"],
    ["Eagle", "Hawk"],
    ["Physical Education", "Health"],
    ["Brain", "Heart"],
    ["Fireplace", "Heater"],
    ["Drought", "Heatwave"],
    ["Plane", "Helicopter"],
    ["Equator", "Hemisphere"],
    ["Decathlon", "Heptathlon"],
    ["Jinx", "Hex"],
    ["Runway", "Highway"],
    ["Climbing", "Hiking"],
    ["Mountain", "Hill"],
    ["Waist", "Hip"],
    ["Elephant", "Hippo"],
    ["Genealogy", "History"],
    ["Assassin's Creed", "Hitman"],
    ["Golf", "Hockey"],
    ["Diwali", "Holi"],
    ["Poinsettia", "Holly"],
    ["Jam", "Honey"],
    ["Cantaloupe", "Honeydew"],
    ["Wasp", "Hornet"],
    ["Terror", "Horror"],
    ["Reindeer", "Horse"],
    ["Unicorn", "Horse"],
    ["Polo", "Horse Racing"],
    ["Motel", "Hostel"],
    ["Eggnog", "Hot Chocolate"],
    ["Geyser", "Hot Spring"],
    ["Home", "Hotel"],
    ["Friends", "How I Met Your Mother"],
    ["Dell", "HP"],
    ["Netflix", "Hulu"],
    ["Fishing", "Hunting"],
    ["Tornado", "Hurricane"],
    ["Groom", "Husband"],
    ["Central Park", "Hyde Park"],
    ["Honda", "Hyundai"],
    ["Yogurt", "Ice Cream"],
    ["Icicle", "Ice Cube"],
    ["Glacier", "Iceberg"],
    ["Snowy", "Icy"],
    ["Flickr", "Imgur"],
    ["Relative", "In-Law"],
    ["The Matrix", "Inception"],
    ["VPN", "Incognito Mode"],
    ["LinkedIn", "Indeed"],
    ["Freedom", "Independence"],
    ["Thumb", "Index Finger"],
    ["Native American", "Indigenous"],
    ["Detective", "Inspector"],
    ["Fascinated", "Interested"],
    ["Library", "Internet"],
    ["Translator", "Interpreter"],
    ["Spider-Man", "Iron Man"],
    ["Annoyed", "Irritated"],
    ["Mistletoe", "Ivy"],
    ["Pumpkin", "Jack-o-lantern"],
    ["Coat", "Jacket"],
    ["Durian", "Jackfruit"],
    ["Ackee", "Jackfruit"],
    ["Prison", "Jail"],
    ["Mission Impossible", "James Bond"],
    ["Cycling", "Jogging"],
    ["Scrapbooking", "Journaling"],
    ["Writer", "Journalist"],
    ["Quest", "Journey"],
    ["Cheerful", "Joyful"],
    ["Karate", "Judo"],
    ["Magic Tricks", "Juggling"],
    ["Soda", "Juice"],
    ["Potion", "Juice"],
    ["Forest", "Jungle"],
    ["Spam", "Junk Mail"],
    ["Saturn", "Jupiter"],
    ["The Avengers", "Justice League"],
    ["Canoe", "Kayak"],
    ["Fencing", "Kendo"],
    ["Teapot", "Kettle"],
    ["Controller", "Keyboard"],
    ["Piano", "Keyboard"],
    ["McDonalds", "KFC"],
    ["Twitch", "Kick"],
    ["Softball", "Kickball"],
    ["Liver", "Kidney"],
    ["Starfruit", "Kiwi"],
    ["Kangaroo", "Koala"],
    ["Asteroid Belt", "Kuiper Belt"],
    ["Taekwondo", "Kung Fu"],
    ["Hanukkah", "Kwanzaa"],
    ["Dungeon", "Labyrinth"],
    ["River", "Lake"],
    ["Rover", "Lander"],
    ["Plymouth Rock", "Landmark"],
    ["Dialect", "Language"],
    ["Candle", "Lantern"],
    ["Mid-Autumn Festival", "Lantern Festival"],
    ["Indiana Jones", "Lara Croft"],
    ["Pantry", "Larder"],
    ["Cosplay", "LARP"],
    ["Paintball", "Laser Tag"],
    ["Restroom", "Lavatory"],
    ["Judge", "Lawyer"],
    ["Bored", "Lazy"],
    ["Groundhog Day", "Leap Day"],
    ["Arm", "Leg"],
    ["Heritage", "Legacy"],
    ["History", "Legend"],
    ["Jeans", "Leggings"],
    ["Cheetah", "Leopard"],
    ["Goodreads", "Letterboxd"],
    ["Calligraphy", "Lettering"],
    ["Kraken", "Leviathan"],
    ["Audi", "Lexus"],
    ["Samsung", "LG"],
    ["Democracy", "Liberty"],
    ["Match", "Lighter"],
    ["Love", "Like"],
    ["Lemon", "Lime"],
    ["WeChat", "Line"],
    ["Cranberry", "Lingonberry"],
    ["Den", "Living Room"],
    ["Snake", "Lizard"],
    ["Camel", "Llama"],
    ["Foyer", "Lobby"],
    ["Crab", "Lobster"],
    ["Bullet Train", "Locomotive"],
    ["Candy Cane", "Lollipop"],
    ["Big Ben", "London Eye"],
    ["Kumquat", "Loquat"],
    ["Harry Potter", "Lord of the Rings"],
    ["Confused", "Lost"],
    ["Gucci", "Louis Vuitton"],
    ["Wishbone", "Lucky Charm"],
    ["Bobsleigh", "Luge"],
    ["Miner", "Lumberjack"],
    ["New Year's Eve", "Lunar New Year"],
    ["Dinner", "Lunch"],
    ["Uber", "Lyft"],
    ["Artificial Intelligence", "Machine Learning"],
    ["Miracle", "Magic"],
    ["Hearthstone", "Magic The Gathering"],
    ["Gravity", "Magnetism"],
    ["Janitor", "Maid"],
    ["CEO", "Manager"],
    ["Walrus", "Manatee"],
    ["Clementine", "Mandarin"],
    ["Pineapple", "Mango"],
    ["Avocado", "Mango"],
    ["Etiquette", "Manners"],
    ["Chimera", "Manticore"],
    ["Triathlon", "Marathon"],
    ["Chalk", "Marker"],
    ["Mall", "Market"],
    ["Engagement", "Marriage"],
    ["Earth", "Mars"],
    ["Swamp", "Marsh"],
    ["Helmet", "Mask"],
    ["Visa", "Mastercard"],
    ["Labor Day", "May Day"],
    ["Ruler", "Measuring Tape"],
    ["Electrician", "Mechanic"],
    ["Yoga", "Meditation"],
    ["Date", "Meeting"],
    ["Jaws", "Megalodon"],
    ["Watermelon", "Melon"],
    ["Papaya", "Melon"],
    ["Monument", "Memorial"],
    ["Independence Day", "Memorial Day"],
    ["Ghostbusters", "Men in Black"],
    ["BMW", "Mercedes"],
    ["Venus", "Mercury"],
    ["Siren", "Mermaid"],
    ["Email", "Message"],
    ["Apple", "Microsoft"],
    ["Smoothie", "Milkshake"],
    ["Solitaire", "Minesweeper"],
    ["Centaur", "Minotaur"],
    ["Gloves", "Mittens"],
    ["Frozen", "Moana"],
    ["Actor", "Model"],
    ["Router", "Modem"],
    ["Humility", "Modesty"],
    ["Demon", "Monster"],
    ["Potala Palace", "Mont Saint-Michel"],
    ["Star", "Moon"],
    ["Sun", "Moon"],
    ["Candlelight", "Moonlight"],
    ["Deer", "Moose"],
    ["Broom", "Mop"],
    ["Ethics", "Morality"],
    ["Midnight", "Morning"],
    ["Grass", "Moss"],
    ["Butterfly", "Moth"],
    ["Engine", "Motor"],
    ["Bicycle", "Motorcycle"],
    ["Mount Everest", "Mount Fuji"],
    ["Rat", "Mouse"],
    ["Keyboard", "Mouse"],
    ["Nose", "Mouth"],
    ["Kickboxing", "Muay Thai"],
    ["Dirt", "Mud"],
    ["Puddle", "Mud"],
    ["Humid", "Muggy"],
    ["Blackberry", "Mulberry"],
    ["Zombie", "Mummy"],
    ["Fresco", "Mural"],
    ["Art", "Music"],
    ["Opera", "Musical"],
    ["Oysters", "Mussels"],
    ["Ketchup", "Mustard"],
    ["Secret", "Mystery"],
    ["Folklore", "Mythology"],
    ["Popcorn", "Nachos"],
    ["Paper", "Napkin"],
    ["Blood Orange", "Navel Orange"],
    ["Galaxy", "Nebula"],
    ["Shoulder", "Neck"],
    ["Son", "Nephew"],
    ["Godson", "Nephew"],
    ["Pluto", "Neptune"],
    ["Scared", "Nervous"],
    ["Bilibili", "Niconico"],
    ["Sister", "Niece"],
    ["Daughter", "Niece"],
    ["Dream", "Nightmare"],
    ["Canon", "Nikon"],
    ["Pasta", "Noodle"],
    ["Memory", "Nostalgia"],
    ["Marshmallow", "Nougat"],
    ["Doctor", "Nurse"],
    ["Playroom", "Nursery"],
    ["Coconut", "Nut"],
    ["Peanut Butter", "Nutella"],
    ["Hurt", "Offended"],
    ["Troll", "Ogre"],
    ["Cyclops", "Ogre"],
    ["Rolex", "Omega"],
    ["Patreon", "OnlyFans"],
    ["Hope", "Optimism"],
    ["Hopeful", "Optimistic"],
    ["Chimpanzee", "Orangutan"],
    ["Choir", "Orchestra"],
    ["Geocaching", "Orienteering"],
    ["Beaver", "Otter"],
    ["Toilet", "Outhouse"],
    ["Roasting Pan", "Oven"],
    ["Tracksuit", "Overalls"],
    ["Clam", "Oyster"],
    ["Colors", "Paint"],
    ["Nightgown", "Pajamas"],
    ["Castle", "Palace"],
    ["Bear", "Panda"],
    ["Tofu", "Paneer"],
    ["Sydney Opera House", "Pantheon"],
    ["Puma", "Panther"],
    ["Kitchen", "Pantry"],
    ["Book", "Paper"],
    ["Canvas", "Paper"],
    ["Origami", "Papercraft"],
    ["Umbrella", "Parasol"],
    ["Lounge", "Parlor"],
    ["Light Year", "Parsec"],
    ["Soulmate", "Partner"],
    ["Wedding", "Party"],
    ["Affection", "Passion"],
    ["Dragon Fruit", "Passion Fruit"],
    ["Macaroni and Cheese", "Pasta"],
    ["Meadow", "Pasture"],
    ["Balcony", "Patio"],
    ["Console", "PC"],
    ["Nectarine", "Peach"],
    ["Parrot", "Peacock"],
    ["Apple", "Pear"],
    ["Guava", "Pear"],
    ["Rock", "Pebble"],
    ["Pen", "Pencil"],
    ["Brush", "Pencil"],
    ["Island", "Peninsula"],
    ["Salami", "Pepperoni"],
    ["Coke", "Pepsi"],
    ["Deodorant", "Perfume"],
    ["Pirates of the Caribbean", "Peter Pan"],
    ["Religion", "Philosophy"],
    ["Ramen", "Pho"],
    ["Painting", "Photo"],
    ["Math", "Physics"],
    ["Chemistry", "Physics"],
    ["Anatomy", "Physiology"],
    ["Times Square", "Piccadilly Circus"],
    ["Cake", "Pie"],
    ["Yoga", "Pilates"],
    ["Astronaut", "Pilot"],
    ["Password", "PIN"],
    ["Christmas Tree", "Pine Tree"],
    ["Xiaohongshu", "Pinterest"],
    ["Byte", "Pixel"],
    ["Star", "Planet"],
    ["Exoplanet", "Planet"],
    ["King Kong", "Planet of the Apes"],
    ["Observatory", "Planetarium"],
    ["Calendar", "Planner"],
    ["Banana", "Plantain"],
    ["Harvest", "Planting"],
    ["Gym", "Playground"],
    ["Tweezers", "Pliers"],
    ["Carpenter", "Plumber"],
    ["Literature", "Poetry"],
    ["Ambulance", "Police Car"],
    ["Ghoul", "Poltergeist"],
    ["Grapefruit", "Pomelo"],
    ["Puddle", "Pond"],
    ["Beach", "Pool"],
    ["Rap", "Pop"],
    ["Carol", "Pop Song"],
    ["Fame", "Popularity"],
    ["Hedgehog", "Porcupine"],
    ["Steak", "Pork Chop"],
    ["Dolphin", "Porpoise"],
    ["Harbor", "Port"],
    ["Thread", "Post"],
    ["Bank", "Post Office"],
    ["Greeting Card", "Postcard"],
    ["Cauldron", "Pot"],
    ["Yam", "Potato"],
    ["Sculpting", "Pottery"],
    ["Weightlifting", "Powerlifting"],
    ["Trick", "Prank"],
    ["Blessing", "Prayer"],
    ["Forecast", "Prediction"],
    ["Gift", "Present"],
    ["Rainbow", "Prism"],
    ["Noob", "Pro"],
    ["Microchip", "Processor"],
    ["Teacher", "Professor"],
    ["Account", "Profile"],
    ["Coding", "Programming"],
    ["Graduation", "Prom"],
    ["Vows", "Promises"],
    ["Plum", "Prune"],
    ["Therapist", "Psychiatrist"],
    ["Psychology", "Psychiatrist"],
    ["Fortnite", "PUBG"],
    ["Penguin", "Puffin"],
    ["Cardigan", "Pullover"],
    ["Wallet", "Purse"],
    ["Tetris", "Puzzle"],
    ["Great Wall", "Pyramids"],
    ["Burrito", "Quesadilla"],
    ["Rice", "Quinoa"],
    ["Exam", "Quiz"],
    ["Subway", "Quiznos"],
    ["Reddit", "Quora"],
    ["Squash", "Racquetball"],
    ["Umbrella", "Raincoat"],
    ["Trench Coat", "Raincoat"],
    ["Snowflake", "Raindrop"],
    ["Rocky", "Rambo"],
    ["Mangosteen", "Rambutan"],
    ["Beatboxing", "Rapping"],
    ["Strawberry", "Raspberry"],
    ["Boysenberry", "Raspberry"],
    ["Astronaut Ice Cream", "Rations"],
    ["Crow", "Raven"],
    ["Bat", "Raven"],
    ["Lasagna", "Ravioli"],
    ["Logic", "Reason"],
    ["Pink", "Red"],
    ["Guilt", "Regret"],
    ["Heartbreak", "Rejection"],
    ["Calm", "Relaxed"],
    ["Artifact", "Relic"],
    ["Veteran's Day", "Remembrance Day"],
    ["Meteorologist", "Reporter"],
    ["Duty", "Responsibility"],
    ["Bathroom", "Restroom"],
    ["Hippopotamus", "Rhino"],
    ["Spine", "Rib"],
    ["Wrapping Paper", "Ribbon"],
    ["Brisket", "Ribs"],
    ["Fried Rice", "Risotto"],
    ["Bridge", "Road"],
    ["Baking", "Roasting"],
    ["Pajamas", "Robe"],
    ["Minecraft", "Roblox"],
    ["Terminator", "RoboCop"],
    ["Skateboarding", "Rollerblading"],
    ["Orbit", "Rotation"],
    ["Intersection", "Roundabout"],
    ["Sudoku", "Rubik's Cube"],
    ["Soccer", "Rugby"],
    ["Yacht", "Sailboat"],
    ["Guacamole", "Salsa"],
    ["Costco", "Sam's Club"],
    ["Slippers", "Sandals"],
    ["Belt", "Sash"],
    ["Sushi", "Sashimi"],
    ["Rocket", "Satellite"],
    ["Gravy", "Sauce"],
    ["Spa", "Sauna"],
    ["Hot Dog", "Sausage"],
    ["Bacon", "Sausage"],
    ["Forehead", "Scalp"],
    ["Snowman", "Scarecrow"],
    ["Creepy", "Scary"],
    ["Knife", "Scissors"],
    ["Wheelchair", "Scooter"],
    ["Grade", "Score"],
    ["Omelet", "Scrambled Eggs"],
    ["Producer", "Screenwriter"],
    ["Pitchfork", "Scythe"],
    ["Pelican", "Seagull"],
    ["Dolphin", "Seal"],
    ["Browser", "Search Engine"],
    ["Receptionist", "Secretary"],
    ["Police", "Security Guard"],
    ["Nintendo", "Sega"],
    ["Martial Arts", "Self Defense"],
    ["Basilisk", "Serpent"],
    ["Cloud", "Server"],
    ["Pilgrim", "Settler"],
    ["Blind Date", "Setup"],
    ["Knitting", "Sewing"],
    ["Soap", "Shampoo"],
    ["Boat", "Ship"],
    ["Mayflower", "Ship"],
    ["Surprised", "Shocked"],
    ["Archery", "Shooting"],
    ["Collecting", "Shopping"],
    ["Pants", "Shorts"],
    ["Downpour", "Shower"],
    ["Scream", "Shriek"],
    ["Fish", "Shrimp"],
    ["Embarrassed", "Shy"],
    ["Roommate", "Sibling"],
    ["Twins", "Siblings"],
    ["Disgusted", "Sickened"],
    ["Rune", "Sigil"],
    ["Telegram", "Signal"],
    ["Peace", "Silence"],
    ["Resident Evil", "Silent Hill"],
    ["Musician", "Singer"],
    ["Serenading", "Singing"],
    ["Bachelor", "Single"],
    ["Faucet", "Sink"],
    ["Colosseum", "Sistine Chapel"],
    ["Scooter", "Skateboard"],
    ["Surfing", "Skating"],
    ["Bone", "Skeleton"],
    ["Snowboarding", "Skiing"],
    ["Uno", "Skip-Bo"],
    ["Dress", "Skirt"],
    ["Skeleton", "Skull"],
    ["Zoom", "Skype"],
    ["Discord", "Slack"],
    ["Tired", "Sleepy"],
    ["Hail", "Sleet"],
    ["Fog", "Smoke"],
    ["Smog", "Smoke"],
    ["Minions", "Smurfs"],
    ["Turtle", "Snail"],
    ["Boots", "Sneakers"],
    ["Billiards", "Snooker"],
    ["Rain", "Snow"],
    ["Skiing", "Snowboarding"],
    ["Jet Ski", "Snowmobile"],
    ["Football", "Soccer"],
    ["Philosophy", "Sociology"],
    ["Stocking", "Sock"],
    ["Hardware", "Software"],
    ["Firefighter", "Soldier"],
    ["Heel", "Sole"],
    ["Eclipse", "Solstice"],
    ["Poem", "Song"],
    ["Mario", "Sonic"],
    ["Ash", "Soot"],
    ["Gelato", "Sorbet"],
    ["Ghost", "Soul"],
    ["Music", "Sound"],
    ["Mayonnaise", "Sour Cream"],
    ["North Pole", "South Pole"],
    ["Time", "Space"],
    ["Rocket", "Spaceship"],
    ["Space Station", "Spaceship"],
    ["Macaroni", "Spaghetti"],
    ["Banshee", "Specter"],
    ["Figure Skating", "Speed Skating"],
    ["Griffin", "Sphinx"],
    ["Mount Rushmore", "Sphinx"],
    ["Cobweb", "Spiderweb"],
    ["Ghost", "Spirit"],
    ["Soul", "Spirit"],
    ["Mickey Mouse", "SpongeBob"],
    ["Fork", "Spoon"],
    ["Dance", "Sport"],
    ["Database", "Spreadsheet"],
    ["Marathon", "Sprint"],
    ["Malware", "Spyware"],
    ["Melon", "Squash"],
    ["Sweet Potato", "Squash"],
    ["Octopus", "Squid"],
    ["Skunk", "Squirrel"],
    ["Secret Admirer", "Stalker"],
    ["Envelope", "Stamp"],
    ["Sun", "Star"],
    ["Star Wars", "Star Trek"],
    ["Animal Crossing", "Stardew Valley"],
    ["Birdwatching", "Stargazing"],
    ["Airport", "Station"],
    ["Calculus", "Statistics"],
    ["Gargoyle", "Statue"],
    ["Eiffel Tower", "Statue of Liberty"],
    ["Water", "Steam"],
    ["Iron", "Steamer"],
    ["Root", "Stem"],
    ["Half-Brother", "Stepbrother"],
    ["Father-in-Law", "Stepfather"],
    ["Mother-in-Law", "Stepmother"],
    ["Soup", "Stew"],
    ["Curry", "Stew"],
    ["Wand", "Stick"],
    ["Emoji", "Sticker"],
    ["Socks", "Stockings"],
    ["Lung", "Stomach"],
    ["Chair", "Stool"],
    ["Traffic Light", "Stop Sign"],
    ["Attic", "Storage Room"],
    ["Poem", "Story"],
    ["Creek", "Stream"],
    ["Super Smash Bros", "Street Fighter"],
    ["Power", "Strength"],
    ["Overwhelmed", "Stressed"],
    ["Teacher", "Student"],
    ["Office", "Study"],
    ["Library", "Study"],
    ["Teddy Bear", "Stuffed Animal"],
    ["Shocked", "Stunned"],
    ["Hovercraft", "Submarine"],
    ["Medium", "Substack"],
    ["Bus Stop", "Subway Station"],
    ["Heir", "Successor"],
    ["Proposal", "Suggestion"],
    ["Necromancer", "Summoner"],
    ["UV Index", "Sunburn"],
    ["Glasses", "Sunglasses"],
    ["Sunrise", "Sunset"],
    ["Batman", "Superman"],
    ["Dentist", "Surgeon"],
    ["Belt", "Suspenders"],
    ["Blood", "Sweat"],
    ["Hoodie", "Sweater"],
    ["Underwear", "Swimsuit"],
    ["Shirt", "T-Shirt"],
    ["Laptop", "Tablet"],
    ["Strategy", "Tactic"],
    ["Hashtag", "Tag"],
    ["Boutique", "Tailor"],
    ["Leftovers", "Takeout"],
    ["Amulet", "Talisman"],
    ["Orange", "Tangerine"],
    ["Tractor", "Tank"],
    ["Ballet", "Tap Dance"],
    ["Ruler", "Tape"],
    ["Spider", "Tarantula"],
    ["Car", "Taxi"],
    ["Uber", "Taxi"],
    ["Coffee", "Tea"],
    ["Family", "Team"],
    ["Zoom", "Teams"],
    ["Flirt", "Tease"],
    ["Fangs", "Teeth"],
    ["WhatsApp", "Telegram"],
    ["Cashier", "Teller"],
    ["Church", "Temple"],
    ["Taj Mahal", "Temple"],
    ["Muscle", "Tendon"],
    ["Ping Pong", "Tennis"],
    ["Gigabyte", "Terabyte"],
    ["Semester", "Term"],
    ["Bonsai", "Terrarium"],
    ["Panicked", "Terrified"],
    ["Pac-Man", "Tetris"],
    ["Grateful", "Thankful"],
    ["Black Friday", "Thanksgiving Eve"],
    ["Twilight", "The Hunger Games"],
    ["Finding Nemo", "The Lion King"],
    ["Game of Thrones", "The Witcher"],
    ["Cinema", "Theater"],
    ["Drama", "Theater"],
    ["Essay", "Thesis"],
    ["Idea", "Thought"],
    ["Needle", "Thread"],
    ["Antiquing", "Thrifting"],
    ["Lightning", "Thunder"],
    ["Stormy", "Thundery"],
    ["Flea", "Tick"],
    ["Scarf", "Tie"],
    ["Cat", "Tiger"],
    ["Lion", "Tiger"],
    ["Instagram", "TikTok"],
    ["Kuaishou", "TikTok"],
    ["Bauble", "Tinsel"],
    ["Cheesecake", "Tiramisu"],
    ["Wheel", "Tire"],
    ["Giant", "Titan"],
    ["Frog", "Toad"],
    ["Bread", "Toast"],
    ["Sled", "Toboggan"],
    ["Baby", "Toddler"],
    ["Finger", "Toe"],
    ["Egg", "Tofu"],
    ["Patience", "Tolerance"],
    ["Persimmon", "Tomato"],
    ["Tooth", "Tongue"],
    ["Flashlight", "Torch"],
    ["Fire Truck", "Tow Truck"],
    ["Skyscraper", "Tower"],
    ["Golden Gate Bridge", "Tower Bridge"],
    ["Alcatraz", "Tower of London"],
    ["Nutcracker", "Toy Soldier"],
    ["Shrek", "Toy Story"],
    ["Tesla", "Toyota"],
    ["Parade", "Traffic"],
    ["Comedy", "Tragedy"],
    ["Bus", "Train"],
    ["Subway", "Tram"],
    ["Fast & Furious", "Transformers"],
    ["Hiking", "Trekking"],
    ["Clan", "Tribe"],
    ["Magic", "Trick"],
    ["Apple Bobbing", "Trick or Treat"],
    ["Unicycle", "Tricycle"],
    ["Yelp", "TripAdvisor"],
    ["Caviar", "Truffle"],
    ["Monsoon", "Tsunami"],
    ["Rose", "Tulip"],
    ["Pinterest", "Tumblr"],
    ["Blouse", "Tunic"],
    ["Bridge", "Tunnel"],
    ["Cave", "Tunnel"],
    ["Chicken", "Turkey"],
    ["Nanny", "Tutor"],
    ["Suit", "Tuxedo"],
    ["Cinema", "TV"],
    ["Midnight", "Twilight"],
    ["YouTube", "Twitch"],
    ["Facebook", "Twitter"],
    ["Weibo", "Twitter"],
    ["Clubhouse", "Twitter Spaces"],
    ["Hummus", "Tzatziki"],
    ["Tomb Raider", "Uncharted"],
    ["Father", "Uncle"],
    ["Spacesuit", "Uniform"],
    ["Cosmos", "Universe"],
    ["School", "University"],
    ["Download", "Upload"],
    ["FedEx", "UPS"],
    ["Frustrated", "Upset"],
    ["Domain", "URL"],
    ["Laundry Room", "Utility Room"],
    ["Honeymoon", "Vacation"],
    ["Canyon", "Valley"],
    ["Overwatch", "Valorant"],
    ["Truck", "Van"],
    ["Safe Room", "Vault"],
    ["Shoelace", "Velcro"],
    ["Porch", "Veranda"],
    ["Forbidden City", "Versailles"],
    ["Angel Falls", "Victoria Falls"],
    ["Photographer", "Videographer"],
    ["Mansion", "Villa"],
    ["City", "Village"],
    ["Thorn", "Vine"],
    ["Orchard", "Vineyard"],
    ["Prophecy", "Vision"],
    ["Podcast", "Vlog"],
    ["Blogging", "Vlogging"],
    ["Mountain", "Volcano"],
    ["Basketball", "Volleyball"],
    ["Pancake", "Waffle"],
    ["Vest", "Waistcoat"],
    ["Chef", "Waiter"],
    ["Running", "Walking"],
    ["Amazon", "Walmart"],
    ["Pecan Pie", "Walnut Pie"],
    ["Broomstick", "Wand"],
    ["Closet", "Wardrobe"],
    ["Cloakroom", "Wardrobe"],
    ["Factory", "Warehouse"],
    ["Sorcerer", "Warlock"],
    ["Hot", "Warm"],
    ["Dishwasher", "Washing Machine"],
    ["Bee", "Wasp"],
    ["Lighthouse", "Watchtower"],
    ["Success", "Wealth"],
    ["Climate", "Weather"],
    ["QQ", "WeChat"],
    ["Heels", "Wedges"],
    ["Flower", "Weed"],
    ["Burger King", "Wendy's"],
    ["Shark", "Whale"],
    ["Corn", "Wheat"],
    ["Kiss", "Whisper"],
    ["Bell", "Whistle"],
    ["Valentine's Day", "White Day"],
    ["Kremlin", "White House"],
    ["Eraser", "Whiteout"],
    ["Woodworking", "Whittling"],
    ["Bride", "Wife"],
    ["Chimney", "Window"],
    ["Door", "Window"],
    ["Surfing", "Windsurfing"],
    ["Kite Surfing", "Windsurfing"],
    ["Beer", "Wine"],
    ["Champagne", "Wine"],
    ["Drumstick", "Wing"],
    ["Autumn", "Winter"],
    ["Summer Solstice", "Winter Solstice"],
    ["Knowledge", "Wisdom"],
    ["Magician", "Wizard"],
    ["Witch", "Wizard"],
    ["Jedi", "Wizard"],
    ["Frying Pan", "Wok"],
    ["Dog", "Wolf"],
    ["Fox", "Wolf"],
    ["Dumpling", "Wonton"],
    ["Blogger", "WordPress"],
    ["Black Hole", "Wormhole"],
    ["Anxious", "Worried"],
    ["Bouquet", "Wreath"],
    ["Boxing", "Wrestling"],
    ["Sumo", "Wrestling"],
    ["Reading", "Writing"],
    ["PlayStation", "Xbox"],
    ["Google", "Yahoo"],
    ["Gym", "Yoga Studio"],
    ["Firstborn", "Youngest"],
    ["Netflix", "YouTube"],
    ["Streamer", "YouTuber"],
    ["Lemon", "Yuzu"],
    ["Giraffe", "Zebra"],
    ["Vacuum", "Zero Gravity"],
    ["Thor", "Zeus"],
    ["Constellation", "Zodiac"],
    ["Aquarium", "Zoo"],
    ["Veterinarian", "Zoologist"],
    ["Botany", "Zoology"],
    ["Cucumber", "Zucchini"]
  ]
};

const CATEGORY_LABELS = {
  easy: "Everyday",
  medium: "Moderate",
  hard: "Abstract",
  mixed: "Mixed",
  all: "All (Mixed Difficulty)"
};

function pickWordPair(difficulty) {
  if (difficulty === "all") {
    const combined = [...WORDS.easy, ...WORDS.medium, ...WORDS.hard, ...WORDS.mixed];
    return combined[Math.floor(Math.random() * combined.length)];
  }
  const pool = WORDS[difficulty] || WORDS.medium;
  return pool[Math.floor(Math.random() * pool.length)];
}

module.exports = { WORDS, CATEGORY_LABELS, pickWordPair };
